<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login </title>
</head>
<body>
<table>

    <form action="/process_login" method="post">
    <tr>
        <td>Имя пользователя :</td>
        <td>
            <input type="text" name="username" id="username">
        </td>
    </tr>
    <tr>
        <td>
         Пароль :
        </td>
        <td>
            <input type="password" name="password" id="password">
        </td>
    </tr>
        <tr>
            <td>
            <input type="submit" value="Войти">
            </td>
        </tr>
        <tr>
            <td>


            </td>
        </tr>
   </form>

</table>
</body>
</html>